name: Package and Upload Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Package Addon
        run: 
          zip -r HungarianMemeCaller-${{ env.VERSION }}.zip * -x "*.git*"

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: HungarianMemeCaller
          path: HungarianMemeCaller-${{ env.VERSION }}.zip
