name: Package and Upload Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package Addon
        run: |
          # Zip the addon files; adjust the path as needed
          zip -r HungarianMemeCaller-${GITHUB_REF##*/}.zip * -x "*.git*"

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: HungarianMemeCaller
          path: HungarianMemeCaller-${GITHUB_REF##*/}.zip

      - name: Upload to CurseForge
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          curl -X POST "https://wow.curseforge.com/api/projects/855370/upload-file" \
          -H "x-api-token: $CF_API_TOKEN" \
          -F "file=@HungarianMemeCaller-${GITHUB_REF##*/}.zip" \
          -F "metadata={\"changelog\": \"Automated release\", \"releaseType\": \"beta\", \"gameVersions\": [\"11.0.5\"]}"
